version: "3.8"

services:

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx_vhost.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - /etc/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    restart: always
  
  app:
    container_name: app
    build: ./
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    restart: always